redis:
  mode: "standalone"    # Options: standalone, sentinel, cluster
  benchmark:
    total: 10000       # 10000 requests default
    parallels: 50        # 2 parallel default
    random_keys: 0         # 0% random and 100% sequential default
    read_percent: 50     # 50% read and 50 write default
    data_size: 3      # 3 bytes default
    ttl: 120            # 300 seconds default
    case: "set_get_random" # Options: set_get_random, set, get, del, pub, sub
  pool:
    pool_size: 10
    min_idle: 2
  standalone:
    addr: 127.0.0.1:6379
    password: "pwd@redis"
    db: 0
  sentinel:
    master_name: "mymaster"
    addrs:
      - "127.0.0.1:26371"
      - "127.0.0.1:26372"
      - "127.0.0.1:26373"
    password: "pwd@redis"
    db: 0
  cluster:
    addrs:
      - "127.0.0.1:6371"
      - "127.0.0.1:6372"
      - "127.0.0.1:6373"
    password: "pwd@redis"
