# TCP协议配置文件
tcp:
  # 连接配置
  connection:
    address: "localhost"       # 服务器地址
    port: 8080                # 服务器端口
    timeout: "30s"            # 连接超时时间
    keep_alive: true          # 启用TCP Keep-Alive
    keep_alive_period: "30s"  # Keep-Alive周期
    
    # 连接池配置
    pool:
      pool_size: 10           # 连接池大小
      min_idle: 1             # 最小空闲连接数
      max_idle: 5             # 最大空闲连接数
      idle_timeout: "300s"    # 空闲连接超时时间
      connection_timeout: "30s" # 创建连接超时时间

  # 基准测试配置
  benchmark:
    total: 1000               # 总操作数
    parallels: 10             # 并发连接数
    data_size: 1024           # 数据包大小（字节）
    duration: "60s"           # 测试持续时间
    read_percent: 80          # 读操作百分比
    random_keys: 1000         # 随机键数量
    test_case: "echo_test"    # 测试用例：echo_test, send_only, receive_only, bidirectional

  # TCP特定配置
  tcp_specific:
    connection_mode: "persistent" # 连接模式：persistent, transient
    no_delay: true            # 禁用Nagle算法
    buffer_size: 4096         # 缓冲区大小
    linger_timeout: -1        # SO_LINGER超时（-1禁用）
    reuse_address: true       # 启用SO_REUSEADDR

# 测试用例说明：
# - echo_test: 回显测试，发送数据并验证响应
# - send_only: 仅发送数据，不等待响应
# - receive_only: 仅接收数据流
# - bidirectional: 双向数据传输测试