# 核心配置示例文件
core:
  # 日志配置
  logging:
    level: "info"              # 日志级别: debug, info, warn, error
    format: "json"             # 日志格式: json, text
    output: "stdout"           # 输出目标: stdout, file, 或文件路径
    file_path: "./logs"        # 日志文件目录
    max_size: "100MB"          # 单个日志文件最大大小
    max_age: 7                 # 日志文件保留天数
    max_backups: 5             # 最大备份文件数
    compress: true             # 是否压缩旧日志文件

  # 报告通用配置
  reports:
    enabled: true              # 是否启用报告
    formats: ["console"]       # 报告格式: console, json, csv, text, all
    output_dir: "./reports"    # 报告输出目录
    file_prefix: "benchmark"   # 报告文件前缀
    include_timestamp: true    # 文件名包含时间戳
    enable_console_report: true # 启用控制台详细报告
    overwrite_existing: false  # 是否覆盖已存在文件

  # 监控配置
  monitoring:
    enabled: true              # 是否启用监控
    metrics_interval: "5s"     # 指标收集间隔
    prometheus:
      enabled: false           # 是否启用Prometheus导出
      port: 9090               # Prometheus导出端口
    statsd:
      enabled: false           # 是否启用StatsD导出
      host: "localhost:8125"   # StatsD服务器地址

  # 全局连接配置
  connection:
    timeout: "30s"             # 默认连接超时
    keep_alive: "30s"          # 连接保持时间
    max_idle_conns: 100        # 最大空闲连接数
    idle_conn_timeout: "90s"   # 空闲连接超时时间