# Kafka配置示例 - 基本生产者测试
kafka:
  brokers:
    - "localhost:9092"
  client_id: "abc-runner-example"
  producer:
    acks: "all"
    batch_size: 16384
    compression: "snappy"
  benchmark:
    default_topic: "test-topic"
    total: 10000
    parallels: 5
    message_size: 1024
    test_case: "produce"