# Kafka配置示例 - 基本生产者测试
kafka:
  brokers:
    - "localhost:9092"
  client_id: "redis-runner-example"
  producer:
    acks: "all"
    batch_size: 16384
    compression: "snappy"
  benchmark:
    default_topic: "test-topic"
    total: 10000
    parallels: 5
    message_size: 1024
    test_case: "produce"
  reports:
    enabled: true
    formats: ["console", "json", "csv"]
    output_dir: "./reports"
    file_prefix: "kafka_performance"
    include_producer_metrics: true
    include_timestamp: true
    enable_console_report: true
    overwrite_existing: false