# HTTP服务端配置文件
protocol: http
host: localhost
port: 8080

# HTTP服务器配置
read_timeout: 30s
write_timeout: 30s
idle_timeout: 60s
max_header_bytes: 1048576  # 1MB

# 响应配置
response:
  default_delay: 0ms
  default_status_code: 200
  default_size: 1024
  content_type: application/json
  enable_compression: false

# 路由配置
routes:
  - path: /
    method: GET
    status_code: 200
    delay: 0ms
    content_type: application/json
    response:
      message: "Hello from abc-runner HTTP test server!"
      protocol: http
      timestamp: 0

  - path: /health
    method: GET
    status_code: 200
    delay: 0ms
    content_type: application/json
    response:
      status: ok
      protocol: http

  - path: /test/fast
    method: GET
    status_code: 200
    delay: 1ms
    content_type: application/json
    response:
      message: "Fast response test"
      delay: "1ms"

  - path: /test/slow
    method: GET
    status_code: 200
    delay: 100ms
    content_type: application/json
    response:
      message: "Slow response test"
      delay: "100ms"

  - path: /test/error
    method: GET
    status_code: 500
    delay: 0ms
    content_type: application/json
    response:
      error: "Internal Server Error"
      message: "Simulated error for testing"

  - path: /test/notfound
    method: GET
    status_code: 404
    delay: 0ms
    content_type: application/json
    response:
      error: "Not Found"
      message: "Resource not found"

# CORS配置
cors:
  enabled: true
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - HEAD
    - OPTIONS
  allowed_headers:
    - "*"
  exposed_headers: []
  allow_credentials: false
  max_age: 3600

# TLS配置
tls:
  enabled: false
  cert_file: ""
  key_file: ""